apiVersion: apps/v1
kind: Deployment
metadata:
  name: athlete-digital-twin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: yourdockerhub/backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: athlete-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: athlete-digital-twin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: yourdockerhub/frontend:latest
        ports:
        - containerPort: 3000
